work/WebApp/Controllers/MarksController.cs
using AutoMapper;
using DAL.Models;
using DAL;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System;
using System.Reflection.Metadata.Ecma335;
using Microsoft.CodeAnalysis.Operations;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace WebApp.Controllers
{
    public class MarksController : Controller
    {
        private readonly StudentDataContext _context;
        Repository repo;
        private readonly IMapper _mapper;
        public MarksController(StudentDataContext context, IMapper mapper)
        {
            _context = context;
            repo = new Repository(_context);
            _mapper = mapper;
        }
        #region view all student data
        public IActionResult ViewStudent()
        {
            List<Models.Marks> lstModelStd = new List<Models.Marks>();
          //List<Models.Marks> lstModelStd1 = new List<Models.Marks>();
            var listStudents = repo.GetList();
            foreach (var mark in listStudents.Item1)
            {
                lstModelStd.Add(_mapper.Map<Models.Marks>(mark));
            }
            foreach (var marks in listStudents.Item2)
            {
                lstModelStd.Add(_mapper.Map<Models.Marks>(marks));
            }
            return View(lstModelStd);
        }
        #endregion
        
        #region View all Marks table data
        public IActionResult ViewMarks()
        {List<Models.Marks> lstModelMarks = new List<Models.Marks>();
            var listMarks=repo.GetMarks();
            foreach (var mark in listMarks) 
            {
                lstModelMarks.Add(_mapper.Map<Models.Marks>(mark));    
            }
            return View(lstModelMarks);
        }
        #endregion
        
        #region update marks
        public IActionResult UpdateMarks(Models.Marks mks)
        {
            return View(mks);
        }
        #endregion
        
        #region update marks post method
        [HttpPost]
        public IActionResult SaveUpdateMarks(Models.Marks marks)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                try
                {
                    status = repo.UpdateMarks(_mapper.Map<Marks>(marks));
                    if (status)
                        return RedirectToAction("ViewMarks");
                    else
                        return View("UpdateMarks");
                }
                catch (System.Exception)
                {
                    return View("UpdateMarks");
                }
            }
            return View("UpdateStudent", marks);
        }
        #endregion
        
        #region delete marks
      
        public IActionResult DeleteMarks(Models.Marks marks)
        {
            return View(marks);
        }
        #endregion
        
        #region delete student method
        [HttpPost]
        public IActionResult SaveDelete(int RollNo,int year)
        {
            bool status = false;
            try
            {
                status = repo.DeleteMarks(RollNo,year);
                if (status)
                {
                    return RedirectToAction("ViewMarks");
                }
                else
                {
                    return View("DeleteMarks");
                }
            }
            catch (Exception)
            {

                return View("DeleteMarks");
            }

        }
        #endregion
        
        #region view all student data
        public IActionResult ViewHighest()
        {
       //List<Models.Marks> lstModelStd1 = new List<Models.Marks>();
            ViewBag.One = repo.Mathsmax();
            ViewBag.Sci = repo.ScienceMax();    
            ViewBag.Three = repo.AvgMax();
            ViewBag.Four = repo.EngMax();
            return View();
        }
        #endregion

        #region add marks
        public IActionResult AddMarks()
        {
            string marksId = repo.GetNextId();
            ViewBag.NextId = marksId;
            return View();
        }
        #endregion

        #region save added students 
        [HttpPost]
        public IActionResult SaveAddMark(Marks marks) 
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                try
                { if (marks.Science == 0 && marks.Maths == 0)
                    {
                        marks.SmAverage = 0;
                    }
                    else { marks.SmAverage = (marks.Science + marks.Maths) / 2; }
                    if (marks.Science == 0 && marks.Maths == 0 && marks.History == 0 && marks.English == 0 && marks.Geography == 0)
                    {
                        marks.MarksAverage = 0;
                    }
                    else
                    {

                        marks.MarksAverage = (marks.Science + marks.Geography + marks.Maths + marks.History + marks.English) / 5;
                    }
                    status = repo.AddMarks(_mapper.Map<Marks>(marks));
                    if (status)
                        return RedirectToAction("ViewMarks");
                    else
                        return View("AddMarks");
                }
                catch (Exception)
                {
                    return View("AddMarks");
                }
            }
            return View("ViewMarks", marks);
        }
        #endregion
    }
}

work/WebApp/Controllers/StudentController.cs
using DAL.Models;
using DAL;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using System.Collections.Generic;
using WebApp.StdRepo;
using System;
using Microsoft.AspNetCore.Http;

namespace WebApp.Controllers
{
    public class StudentController : Controller
    {
        private readonly StudentDataContext _context;
        Repository repo;
        private readonly IMapper _mapper;
        public StudentController(StudentDataContext context, IMapper mapper)
        {
            _context = context;
            repo = new Repository(_context);
            _mapper = mapper;
        }
        #region for view of AddStudent
        public IActionResult AddStudent()
        {
            return View();
        }
        #endregion

        #region View students data who have scored more than 90% for past two years
        public IActionResult ViewStudent()
        {
            List<Models.Student> lstModelStd = new List<Models.Student>();
            var listStudents = repo.GetStudents();
            foreach (var std in listStudents)
            {
                lstModelStd.Add(_mapper.Map<Models.Student>(std));
            }
            return View(lstModelStd);
        }
        #endregion

        #region saving students data in student table
        [HttpPost]
        public IActionResult SaveAddStudents(Models.Student student)
        {
            bool status = false;
            try
            {
                if (ModelState.IsValid)
                {
                    status = repo.AddStudent(_mapper.Map<Student>(student));
                    if (status)
                        return RedirectToAction("AddStudent", student);
                    else
                        return View("Error");
                }
            }
            catch (System.Exception)
            {

                return View("Error");
            }
            return View("AddStudent", student);
        }
        #endregion

        #region update student
        public IActionResult UpdateStudent(Models.Student std)
        {
            return View(std);
        }
        #endregion

        #region update student post method
        [HttpPost]
        public IActionResult SaveUpdateStudents(Models.Student student)
        {
            bool status = false;
            if (ModelState.IsValid)
            {
                try
                {
                    status = repo.UpdateStudent(_mapper.Map<Student>(student));
                    if (status)
                        return RedirectToAction("ViewStudent");
                    else
                        return View("Error");
                }
                catch (System.Exception)
                {
                    return View("Error");
                }
            }
            return View("UpdateStudent", student);
        }
        #endregion

        #region delete student
        public IActionResult DeleteStudent(Models.Student student)
        {
            return View(student);
        }
        #endregion
        
        #region delete student method
        [HttpPost]
        public IActionResult SaveDelete(int RollNo)
        {
            bool status = false;
            try
            {
                status = repo.DeleteStd(RollNo);
                if (status)
                {
                    return RedirectToAction("ViewStudent");
                }
                else
                {
                    return View("Error");
                }
            }
            catch (Exception)
            {

                return View("Error");
            }
         
        }
        #endregion
    }
}

work/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

work/WebApp/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <!-- <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApp</a> -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Login" class="navbar-brand">Student Management</a>
              <div class="navbar-collapse collapse">
               <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Marks" asp-action="ViewStudent">View Students &nbsp; </a></li>
                        <li><a asp-area="" asp-controller="Student" asp-action="AddStudent">AddStudents &nbsp;</a></li>
                        <li><a asp-area="" asp-controller="Student" asp-action="ViewStudent">ViewAllStudents &nbsp;</a></li>
                        <li><a asp-area="" asp-controller="Marks" asp-action="AddMarks">AddMarks &nbsp;</a></li>
                        <li><a asp-area="" asp-controller="Marks" asp-action="ViewMarks">ViewAllMarks &nbsp;</a></li>
                        <li><a asp-area="" asp-controller="Marks" asp-action="ViewHighest">ViewCurrentHigh &nbsp;</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <br />
            <br />
            <footer style="bottom:0%;position:fixed;width:80%;text-align:center;">
                <hr />
                <p>&copy; @DateTime.Now.Year - @@Home</p>
            </footer>


        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>